private
resourceData
	" Answer a CSV formatted <String> with ISO data. Data is taken from wikitable at https://en.wikipedia.org/wiki/ISO_3166-1 "
	^ 'Afghanistan;AF;AFG;004;AF
Åland Islands;AX;ALA;248;AX
Albania;AL;ALB;008;AL
Algeria;DZ;DZA;012;DZ
American Samoa;AS;ASM;016;AS
Andorra;AD;AND;020;AD
Angola;AO;AGO;024;AO
Anguilla;AI;AIA;660;AI
Antarctica;AQ;ATA;010;AQ
Antigua and Barbuda;AG;ATG;028;AG
Argentina;AR;ARG;032;AR
Armenia;AM;ARM;051;AM
Aruba;AW;ABW;533;AW
Australia;AU;AUS;036;AU
Austria;AT;AUT;040;AT
Azerbaijan;AZ;AZE;031;AZ
Bahamas;BS;BHS;044;BS
Bahrain;BH;BHR;048;BH
Bangladesh;BD;BGD;050;BD
Barbados;BB;BRB;052;BB
Belarus;BY;BLR;112;BY
Belgium;BE;BEL;056;BE
Belize;BZ;BLZ;084;BZ
Benin;BJ;BEN;204;BJ
Bermuda;BM;BMU;060;BM
Bhutan;BT;BTN;064;BT
Bolivia (Plurinational State of);BO;BOL;068;BO
Bonaire, Sint Eustatius and Saba;BQ;BES;535;BQ
Bosnia and Herzegovina;BA;BIH;070;BA
Botswana;BW;BWA;072;BW
Bouvet Island;BV;BVT;074;BV
Brazil;BR;BRA;076;BR
British Indian Ocean Territory;IO;IOT;086;IO
Brunei Darussalam;BN;BRN;096;BN
Bulgaria;BG;BGR;100;BG
Burkina Faso;BF;BFA;854;BF
Burundi;BI;BDI;108;BI
Cambodia;KH;KHM;116;KH
Cameroon;CM;CMR;120;CM
Canada;CA;CAN;124;CA
Cabo Verde;CV;CPV;132;CV
Cayman Islands;KY;CYM;136;KY
Central African Republic;CF;CAF;140;CF
Chad;TD;TCD;148;TD
Chile;CL;CHL;152;CL
China;CN;CHN;156;CN
Christmas Island;CX;CXR;162;CX
Cocos (Keeling) Islands;CC;CCK;166;CC
Colombia;CO;COL;170;CO
Comoros;KM;COM;174;KM
Republic of the Congo|Congo;CG;COG;178;CG
Congo (Democratic Republic of the);CD;COD;180;CD
Cook Islands;CK;COK;184;CK
Costa Rica;CR;CRI;188;CR
Côte d''Ivoire;CI;CIV;384;CI
Croatia;HR;HRV;191;HR
Cuba;CU;CUB;192;CU
Curaçao;CW;CUW;531;CW
Cyprus;CY;CYP;196;CY
Czech Republic;CZ;CZE;203;CZ
Denmark;DK;DNK;208;DK
Djibouti;DJ;DJI;262;DJ
Dominica;DM;DMA;212;DM
Dominican Republic;DO;DOM;214;DO
Ecuador;EC;ECU;218;EC
Egypt;EG;EGY;818;EG
El Salvador;SV;SLV;222;SV
Equatorial Guinea;GQ;GNQ;226;GQ
Eritrea;ER;ERI;232;ER
Estonia;EE;EST;233;EE
Ethiopia;ET;ETH;231;ET
Falkland Islands (Malvinas);FK;FLK;238;FK
Faroe Islands;FO;FRO;234;FO
Fiji;FJ;FJI;242;FJ
Finland;FI;FIN;246;FI
France;FR;FRA;250;FR
French Guiana;GF;GUF;254;GF
French Polynesia;PF;PYF;258;PF
French Southern Territories;TF;ATF;260;TF
Gabon;GA;GAB;266;GA
Gambia;GM;GMB;270;GM
Georgia (country)|Georgia;GE;GEO;268;GE
Germany;DE;DEU;276;DE
Ghana;GH;GHA;288;GH
Gibraltar;GI;GIB;292;GI
Greece;GR;GRC;300;GR
Greenland;GL;GRL;304;GL
Grenada;GD;GRD;308;GD
Guadeloupe;GP;GLP;312;GP
Guam;GU;GUM;316;GU
Guatemala;GT;GTM;320;GT
Guernsey;GG;GGY;831;GG
Guinea;GN;GIN;324;GN
Guinea-Bissau;GW;GNB;624;GW
Guyana;GY;GUY;328;GY
Haiti;HT;HTI;332;HT
Heard Island and McDonald Islands;HM;HMD;334;HM
Vatican City State|Holy See;VA;VAT;336;VA
Honduras;HN;HND;340;HN
Hong Kong;HK;HKG;344;HK
Hungary;HU;HUN;348;HU
Iceland;IS;ISL;352;IS
India;IN;IND;356;IN
Indonesia;ID;IDN;360;ID
Iran (Islamic Republic of);IR;IRN;364;IR
Iraq;IQ;IRQ;368;IQ
Republic of Ireland|Ireland;IE;IRL;372;IE
Isle of Man;IM;IMN;833;IM
Israel;IL;ISR;376;IL
Italy;IT;ITA;380;IT
Jamaica;JM;JAM;388;JM
Japan;JP;JPN;392;JP
Jersey;JE;JEY;832;JE
Jordan;JO;JOR;400;JO
Kazakhstan;KZ;KAZ;398;KZ
Kenya;KE;KEN;404;KE
Kiribati;KI;KIR;296;KI
North Korea|Korea (Democratic People''s Republic of);KP;PRK;408;KP
Korea (Republic of);KR;KOR;410;KR
Kuwait;KW;KWT;414;KW
Kyrgyzstan;KG;KGZ;417;KG
Lao People''s Democratic Republic;LA;LAO;418;LA
Latvia;LV;LVA;428;LV
Lebanon;LB;LBN;422;LB
Lesotho;LS;LSO;426;LS
Liberia;LR;LBR;430;LR
Libya;LY;LBY;434;LY
Liechtenstein;LI;LIE;438;LI
Lithuania;LT;LTU;440;LT
Luxembourg;LU;LUX;442;LU
Macao;MO;MAC;446;MO
Republic of Macedonia|Macedonia (the former Yugoslav Republic of);MK;MKD;807;MK
Madagascar;MG;MDG;450;MG
Malawi;MW;MWI;454;MW
Malaysia;MY;MYS;458;MY
Maldives;MV;MDV;462;MV
Mali;ML;MLI;466;ML
Malta;MT;MLT;470;MT
Marshall Islands;MH;MHL;584;MH
Martinique;MQ;MTQ;474;MQ
Mauritania;MR;MRT;478;MR
Mauritius;MU;MUS;480;MU
Mayotte;YT;MYT;175;YT
Mexico;MX;MEX;484;MX
Micronesia (Federated States of);FM;FSM;583;FM
Moldova (Republic of);MD;MDA;498;MD
Monaco;MC;MCO;492;MC
Mongolia;MN;MNG;496;MN
Montenegro;ME;MNE;499;ME
Montserrat;MS;MSR;500;MS
Morocco;MA;MAR;504;MA
Mozambique;MZ;MOZ;508;MZ
Myanmar;MM;MMR;104;MM
Namibia;NA;NAM;516;NA
Nauru;NR;NRU;520;NR
Nepal;NP;NPL;524;NP
Netherlands;NL;NLD;528;NL
New Caledonia;NC;NCL;540;NC
New Zealand;NZ;NZL;554;NZ
Nicaragua;NI;NIC;558;NI
Niger;NE;NER;562;NE
Nigeria;NG;NGA;566;NG
Niue;NU;NIU;570;NU
Norfolk Island;NF;NFK;574;NF
Northern Mariana Islands;MP;MNP;580;MP
Norway;NO;NOR;578;NO
Oman;OM;OMN;512;OM
Pakistan;PK;PAK;586;PK
Palau;PW;PLW;585;PW
State of Palestine|Palestine, State of;PS;PSE;275;PS
Panama;PA;PAN;591;PA
Papua New Guinea;PG;PNG;598;PG
Paraguay;PY;PRY;600;PY
Peru;PE;PER;604;PE
Philippines;PH;PHL;608;PH
Pitcairn;PN;PCN;612;PN
Poland;PL;POL;616;PL
Portugal;PT;PRT;620;PT
Puerto Rico;PR;PRI;630;PR
Qatar;QA;QAT;634;QA
Réunion;RE;REU;638;RE
Romania;RO;ROU;642;RO
Russian Federation;RU;RUS;643;RU
Rwanda;RW;RWA;646;RW
Saint Barthélemy;BL;BLM;652;BL
Saint Helena, Ascension and Tristan da Cunha;SH;SHN;654;SH
Saint Kitts and Nevis;KN;KNA;659;KN
Saint Lucia;LC;LCA;662;LC
Saint Martin (French part);MF;MAF;663;MF
Saint Pierre and Miquelon;PM;SPM;666;PM
Saint Vincent and the Grenadines;VC;VCT;670;VC
Samoa;WS;WSM;882;WS
San Marino;SM;SMR;674;SM
Sao Tome and Principe;ST;STP;678;ST
Saudi Arabia;SA;SAU;682;SA
Senegal;SN;SEN;686;SN
Serbia;RS;SRB;688;RS
Seychelles;SC;SYC;690;SC
Sierra Leone;SL;SLE;694;SL
Singapore;SG;SGP;702;SG
Sint Maarten (Dutch part);SX;SXM;534;SX
Slovakia;SK;SVK;703;SK
Slovenia;SI;SVN;705;SI
Solomon Islands;SB;SLB;090;SB
Somalia;SO;SOM;706;SO
South Africa;ZA;ZAF;710;ZA
South Georgia and the South Sandwich Islands;GS;SGS;239;GS
South Sudan;SS;SSD;728;SS
Spain;ES;ESP;724;ES
Sri Lanka;LK;LKA;144;LK
Sudan;SD;SDN;729;SD
Suriname;SR;SUR;740;SR
Svalbard and Jan Mayen;SJ;SJM;744;SJ
Swaziland;SZ;SWZ;748;SZ
Sweden;SE;SWE;752;SE
Switzerland;CH;CHE;756;CH
Syrian Arab Republic;SY;SYR;760;SY
Taiwan;TW;TWN;158;TW
Tajikistan;TJ;TJK;762;TJ
Tanzania, United Republic of;TZ;TZA;834;TZ
Thailand;TH;THA;764;TH
Timor-Leste;TL;TLS;626;TL
Togo;TG;TGO;768;TG
Tokelau;TK;TKL;772;TK
Tonga;TO;TON;776;TO
Trinidad and Tobago;TT;TTO;780;TT
Tunisia;TN;TUN;788;TN
Turkey;TR;TUR;792;TR
Turkmenistan;TM;TKM;795;TM
Turks and Caicos Islands;TC;TCA;796;TC
Tuvalu;TV;TUV;798;TV
Uganda;UG;UGA;800;UG
Ukraine;UA;UKR;804;UA
United Arab Emirates;AE;ARE;784;AE
United Kingdom of Great Britain and Northern Ireland;GB;GBR;826;GB
United States of America;US;USA;840;US
United States Minor Outlying Islands;UM;UMI;581;UM
Uruguay;UY;URY;858;UY
Uzbekistan;UZ;UZB;860;UZ
Vanuatu;VU;VUT;548;VU
Venezuela (Bolivarian Republic of);VE;VEN;862;VE
Viet Nam;VN;VNM;704;VN
British Virgin Islands|Virgin Islands (British);VG;VGB;092;VG
United States Virgin Islands|Virgin Islands (U.S.);VI;VIR;850;VI
Wallis and Futuna;WF;WLF;876;WF
Western Sahara;EH;ESH;732;EH
Yemen;YE;YEM;887;YE
Zambia;ZM;ZMB;894;ZM
Zimbabwe;ZW;ZWE;716;ZW
'